spring:
  thymeleaf:
    cache: false
    #    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html

jasypt:
  encryptor:
    password: newwbbie